# Generated by Django 4.2.3 on 2023-07-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=100)),
                ('descripcionCiudad', models.TextField()),
                ('imagenCiudad', models.ImageField(upload_to='destinations/images/')),
                ('precioTour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ofertaTour', models.BooleanField(default=False)),
            ],
        ),
    ]
